spring.application.name=bionicpro-auth

server.port=8090
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

# Keycloak
keycloak.server-url=http://keycloak:8080
keycloak.realm=reports-realm
keycloak.client-id=reports-frontend

token.encryption.secret=mySup3rSecretKeyForAES123!

app.redirect-uri=http://localhost:3000/callback

spring.datasource.url=jdbc:postgresql://postgres:5432/airflow
spring.datasource.username=airflow
spring.datasource.password=airflow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.endpoint=http://minio:9000
minio.access-key=minio_user
minio.secret-key=minio_password
minio.bucket-name=reports
minio.public-url=http://localhost:8082/reports

clickhouse.url=jdbc:clickhouse://clickhouse:8123/default?user=reporter&password=&compress=0
clickhouse.driver-class=com.clickhouse.jdbc.ClickHouseDriver
logging.level.com.clickhouse=DEBUG